name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:   # allows manual runs

jobs:
  dev-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests (DEV)
        run: npx playwright test --project=dev
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-dev
          path: playwright-report/
          retention-days: 30

  uat-tests:
    needs: dev-tests
    if: github.event_name == 'workflow_dispatch' # only run manually
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests (UAT)
        run: npx playwright test --project=uat
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report-uat
          path: playwright-report/
          retention-days: 30

  prod-tests:
    needs: uat-tests
    if: github.event_name == 'workflow_dispatch' # only run manually
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests (PROD)
        run: npx playwright test --project=prod
      - uses: actions/upload-artifact@v4
        with:
          name: playwright-report-prod
          path: playwright-report/
          retention-days: 30
